version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: always
    container_name: TicketerDatabaseProduction
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/TicketerDatabaseProduction/data
      - postgres_backup:/var/lib/TicketerDatabaseProduction/backups
    environment:
      POSTGRES_DB: Ticketer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  redis:
    image: redis:alpine
    restart: always
    container_name: TicketerCacheProduction
    ports:
      - '6379:6379'
    volumes:
      - ~/redisdata:/data
volumes:
  postgres_data:
  postgres_backup:
