name: Ticketer Deploy To Production

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Deploying to development using SSH Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: ~/Projects/TicketerProduction/scripts/deploytoproduction.sh
        command_timeout: "2m"
